### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Cram3r95** [schmidt-ju/argoverse-navmap#1]
Amazing work, when do you plan to release the code?

**Comment by schmidt-ju** [comment]
Hey :D

code is released now.


Julian

**Comment by Cram3r95** [comment]
I will run the knowledge-distillation experiments again, since they did not work for me with the GANet method, removing map information, though in that case it was more difficult since I want to get the same accuracy without physical information.

I will keep you updated. Thank you my friend.
